default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medicalbook_development
  username: postgres
  password:
  host: localhost
  port: 5432


production:
  # <<: *default
  adapter: postgresql-crystalline-95476
  database: d3t6ua1n90m0qi
  username: haasnqcxhhlmkw
  password: 5fdbf1f9e290eff7ed8f23b7af8b4ebc4b2f47f78605123a55b02c7ea44855ad
  host: ec2-23-21-238-246.compute-1.amazonaws.com
  port: 5432

test:
  <<: *default
  database: medicalbook_tests
